backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

display_url: https://creativinaintedecafea.ro

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Meta Title", name: title, widget: string}
          - {label: "Meta Description", name: descriere, widget: text}
          - {label: "Story", name: story, widget: object, fields: [
              {label: "Subtitlu", name: "subtitle", widget: string},
              {label: "Titlu", name: "titlu", widget: string},
              {label: "Text", name: text, widget: text}]}
          - {label: "Eveniment", name: eveniment, widget: object, fields: [
              {label: "Subtitlu", name: "subtitlu", widget: string},
              {label: "Titlu", name: "titlu", widget: "string"},
              {label: "Descriere", name: "descriere", widget: "markdown"},
              {label: "Detalii", name: "detalii", widget: "string"},
              {label: "Imagine", name: "image", widget: "image", allow_multiple: false, default: "img/cana-madalina.png"},
              {label: "Label Buton", name: "buton_label", widget: "string"},
              {label: "Link Buton", name: "buton_link", widget: "string"}]}
          - {label: "Susținători", name: sustinatori, widget: object, fields: [
              {label: "Titlu", name: "titlu", widget: "string"},
              {label: "Descriere", name: "descriere", widget: "markdown"}]}
          - {label: "Contact", name: "contact", widget: "object", fields: [
              {label: "Titlu", name: "titlu", widget: string},
              {label: "Descriere", name: "descriere", widget: "markdown"}]}
      - file: "site/content/newsletter/_index.md"
        label: "Newsletter"
        name: "newsletter"
        fields:
          - {label: "Meta Title", name: title, widget: string}
          - {label: "Meta Description", name: descriere, widget: text}
          - {label: "Story", name: story, widget: object, fields: [
              {label: "Subtitlu", name: "subtitle", widget: string},
              {label: "Titlu", name: "titlu", widget: string},
              {label: "Text", name: text, widget: text},
              {label: "Imagine", name: "image", widget: "image", allow_multiple: false, default: "img/avatar-oana-bg-primary-2.jpg"}]}
          - {label: "Newsletter", name: newsletter, widget: object, fields: [
              {label: "Subtitlu", name: "subtitle", widget: string},
              {label: "Titlu", name: "title", widget: "string"},
              {label: "Text", name: text, widget: text},
              {label: "Imagine", name: "image", widget: "image", allow_multiple: false, default: "img/-cic-george-rosu-mug.png"}]}
